package com.example.gerenciamentodejogos

val NOME_DB = "JogosLoteria.db"
val VERSAO_DB = 1
val TABELA_RESULTADOS = "TBResultados"
val SCRIPT_CRIAR_TABELA_RESULTADOS = "CREATE TABLE $TABELA_RESULTADOS (ID INTEGER PRIMARY KEY AUTOINCREMENT," +
        "TipoJogo INTEGER NOT NULL, Concurso INTEGER NOT NULL, Resultado TEXT NOT NULL);"

val TELA_INICIAL = 0
val TELA_LOGIN = 1
val TELA_CADASTRO = 2
val TELA_PERFIL = 3
val TELA_RESULTADOS = 4
val TELA_APOSTAS = 5

